title: Coming Soon | Iliana lopez Blog
email: your-email@domain.com
description: This is a coming soon landing page for a upcoming blog website.
baseurl: ""
url: https://ilianalopezblog.com
enforce_ssl: ilianalopezblog.com

# Google services
google_analytics: UA-100374407-1

markdown: kramdown

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
