title: Coming Soon | Iliana lopez Blog
email: your-email@domain.com
description: This is a coming soon landing page for a upcoming blog website.
baseurl: "/coming-soon" 
url: "" 

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
